main: net.countercraft.runner.Runner
name: ${project.name}
version: ${project.version}
authors: [AJCStriker, koesie10]
database: false
description: ${project.description}
startup: postworld
url: ${project.url}
commands:
  reloadrunner:
    description: Reload Runner configuration file from disk
    permission: runner.reload
    usage: /<command>
permissions:
  runner.*:
    description: Gives access to all Runner related commands
    children:
      runner.reload: true
  runner.reload:
    description: Reload Runner configuration file from disk
    default: op